on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: ImageMagick/ImageMagick-Windows
        ref: refs/heads/master
        fetchDepth: 1

    - name: Clone repositories
      run: |
        cd %RUNNER_WORKSPACE%\ImageMagick-Windows
        CloneRepositories.cmd https://github.com/ImageMagick shallow

    - name: Build configure
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd %RUNNER_WORKSPACE%\ImageMagick-Windows\VisualMagick\configure
        devenv /upgrade configure.vcxproj
        msbuild configure.sln /m /t:Rebuild /p:Configuration=Release,Platform=Win32

    - name: Configure ImageMagick
      run: |
        cd %RUNNER_WORKSPACE%\ImageMagick-Windows\VisualMagick\configure
        configure.exe /noWizard /VS2019 /x64 /smtd

    - name: Build ImageMagick
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd %RUNNER_WORKSPACE%\ImageMagick-Windows\VisualMagick
        msbuild VisualStaticMTD.sln /m /t:Rebuild /p:Configuration=Release,Platform=x64
